In [1]:
# February 12st, 2020

# This script compares patent and citing in each classification system
# Second level matches specifications of Nemet and Johnson 2012
# Previous versions are not working and they are difficult to debug

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
import seaborn as sns

import sys
sys.path.append('/home/rkogeyam/scripts/')
sys.path.append('scripts/')

from determinants_scripts import classes, dtypes

from classification import preprocessing

citation='data/cleanuspatentcitation.csv'

usecols=['uuid', 'patent_id', 'citation_id']
df=pd.read_csv(citation, usecols=usecols)

In [3]:
%matplotlib inline

In [4]:
sns.set()

1-Match class to patent_id and to citation_id
2-Create a variable coded with 1 if the classes are different, 0 if they are the same
3

In [5]:


#create classes dataset
class_df=pd.read_csv('data/wipo.csv', dtype=object, usecols=[0,1,2])
class_df=class_df.astype(str)
class_df=class_df.set_index('id')

# for class_system in class_systems:
#     classification = 'data/'+class_system+'.csv'
#     class_x=pd.read_csv(classification, dtype=object, usecols=[0,1,2])
#     class_x=class_x.astype(str)
#     class_x=class_x.set_index('id')
#     class_df=class_df.join(class_x)

In [6]:
class_df.dtypes

wipo_sector_id    object
wipo_field_id     object
dtype: object

In [7]:
df=df.astype(str)
df.set_index('patent_id', inplace=True)

In [8]:
df.dtypes

uuid           object
citation_id    object
dtype: object

In [9]:
df=df.join(class_df)

In [10]:
df.head()
# dimensions=list(df.columns)
# dimensions.remove('uuid')
# dimensions.remove('citation_id')
# dimensions = [sub.replace('_id', '') for sub in dimensions]

                              uuid citation_id wipo_sector_id wipo_field_id
3930271  mok3net9ll9apdxvjvf7r0mjb     2379430              4            33
3930271  zvlxv3wtw969uvcd9azanhlwr     2782422              4            33
3930272  6ddwoi89ailxhwrmj0ehi1z51     2560109              4            33
3930272  77qebcired4jpt5gc24ynddl1     2545289              4            33
3930272  af2k64rnid999g4g0hdutm75o     1549144              4            33

In [11]:
# df.describe()

In [12]:
# df.set_index('uuid', inplace=True)
# df.select_dtypes(include=[np.number]).to_csv('data/int_ext_cit_v2.csv')

In [13]:
df.set_index('citation_id', inplace=True)
df=df.join(class_df, lsuffix='_pat', rsuffix='_cit')
# df.describe()

In [14]:
df.set_index('uuid')
df['wipo_sector_ext']=np.where(df.loc[:,'wipo_sector_id_pat'] != df.loc[:,'wipo_sector_id_cit'], 1, 0)
df['wipo_field_ext']=np.where(df.loc[:,'wipo_field_id_pat'] != df.loc[:,'wipo_field_id_cit'], 1, 0)
df.loc[df.loc[:,'wipo_sector_id_pat'].isnull(), 'wipo_sector_ext'] = np.nan
df.loc[df.loc[:,'wipo_field_id_pat'].isnull(), 'wipo_field_ext'] = np.nan 
df.loc[df.loc[:,'wipo_sector_id_cit'].isnull(), 'wipo_sector_ext'] = np.nan
df.loc[df.loc[:,'wipo_field_id_cit'].isnull(), 'wipo_field_ext'] = np.nan

In [15]:
df.describe()

/home/applications/anaconda3/4.2.0/lib/python3.5/site-packages/numpy/lib/function_base.py:4269: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

       wipo_sector_ext  wipo_field_ext
count     7.075631e+07    7.075631e+07
mean      1.970123e-01    3.719768e-01
std       3.977417e-01    4.833322e-01
min       0.000000e+00    0.000000e+00
25%                NaN             NaN
50%                NaN             NaN
75%                NaN             NaN
max       1.000000e+00    1.000000e+00

In [16]:
df.sample(n=50)

,uuid,wipo_sector_id_pat,wipo_field_id_pat,wipo_sector_id_cit,wipo_field_id_cit,wipo_sector_ext,wipo_field_ext
5461390,gub8nzmrvp9lb9twewrihwo41,2,12,2,12,0.0,0.0
6381726,ykp0pymbu2tv5261g4sviliqe,1,05,1,05,0.0,0.0
6196963,vedhvcn6pkeg5mee8jksf8jsq,2,13,2,13,0.0,0.0
3204795,31gcaiyiooh74zr53m0zo442p,3,25,NaN,NaN,NaN,NaN
3405228,u1a5m43gdgo01x9npux1htaqm,3,31,NaN,NaN,NaN,NaN
4793069,xx4baxd1ead0ci2sfbd9gs3eu,NaN,NaN,1,01,NaN,NaN
7818689,4c4ihe7vbcp0cao3c4wqjiqo2,NaN,NaN,1,06,NaN,NaN
6289993,iaff1bkd8nlc5k5ox6h3a8n8l,4,35,4,35,0.0,0.0
6509291,xixo0px37vc5dwe22wmt72hgt,0,19,0,23,0.0,1.0
5379340,bknh7cbtdro1j4dpswsbjme6g,NaN,NaN,1,04,NaN,NaN
6492347,bfmzgdgys7cn5znu9ddaqkgy6,0,16,0,14,0.0,1.0
4754589,bazy3xxua58s4imsobqg9ckue,4,35,3,29,1.0,1.0
4024088,0dhu5ftd27vrk58vi9ddd86ol,3,29,3,29,0.0,0.0
5978484,hl62z4tujkkpa2w7d2t61rtw9,1,04,1,06,0.0,1.0
6577726,3jhprskqg2e0ehr0oan9htjni,1,06,1,07,0.0,1.0
5141748,wyvacd36tcw6z8bcx6r6wccj3,0,16,0,16,0.0,0.0
4080564,f0jbow75477qt5wmhnk0zfhrm,2,10,1,01,1.0,1.0
D505381,r8qkhrhad1utmtq0yi44zkk6x,NaN,NaN,NaN,NaN,NaN,NaN
6376518,sd37uklks1ms1fb0yks5dnaed,0,14,0,14,0.0,0.0
4642683,tyt5dh2a3etfbfw4w5dt020sl,1,03,1,03,0.0,0.0
2807912,gkarwdhqzde2b8jyhdw8yz0a0,0,23,NaN,NaN,NaN,NaN
4536945,yb3tlai5vc0yom076sf9g58w8,1,08,1,08,0.0,0.0
2813996,ndax3j2n7yi0fhy9vrf1pgdrh,1,01,NaN,NaN,NaN,NaN
3938818,8o318zil7h8f29xidu7dyh1c7,3,25,3,25,0.0,0.0
5396559,no5edugvpcm6qfp6ss301f0xm,1,02,4,34,1.0,1.0
4408244,h33s4xh7olyrzwq7y64n3clr8,1,01,1,01,0.0,0.0
6795323,mj7dmh15l0ck2x4un5znjgvea,1,01,1,01,0.0,0.0
7523045,1vldcilkwxz4r7p0nbij2c0mh,1,07,1,07,0.0,0.0
6978264,43nwuwii7fgtkc3biocvhe226,1,06,1,06,0.0,0.0
D471594,4gvdzwrg7xcu0bdg9myjb85jd,4,33,NaN,NaN,NaN,NaN
7633515,7v98fyyokx8v7unl693eow666,1,03,1,03,0.0,0.0
8105720,gadnlanf76ybr5f05s61suks6,1,07,1,01,0.0,1.0
5091858,g7jqqo4ne0l0geecu5toc3cph,3,27,3,27,0.0,0.0
6301068,d96l2seoptcjb02qhik6ikdrm,1,06,1,02,0.0,1.0
6243522,mg54rr1jon4o91pnib07phbem,2,09,2,09,0.0,0.0
8366019,1wn2726ygr8epbthawqfqqige,4,35,0,23,1.0,1.0
6521970,m9ie7z1sz2ftn5pu0n3w2ntd4,0,14,1,08,1.0,1.0
5019882,fy5gh9l77ousq9eywj1k7g0fz,1,08,1,08,0.0,0.0
8225741,oubuwa3xo4ynith7ii7v9yibd,0,21,0,21,0.0,0.0
5992601,l0m7x8wgjopo84mlx6t8o9mnn,2,12,2,12,0.0,0.0
4593788,azv416n2a06wb8oy697l75s35,4,34,2,13,1.0,1.0
4345251,2tn4h1slhokb0q5bfo6rfmgr6,1,05,2,10,1.0,1.0
5589828,cteljvvmuhl5d2cvtpgderb39,3,25,1,06,1.0,1.0
4753984,p9i1nlkwxs1nt7rn1lkkhh8ww,0,15,0,16,0.0,1.0
1258431,3a7w1v7wk00qoknd60ybawyzb,3,32,NaN,NaN,NaN,NaN
2599706,1zebwwsitrrhcowyb6rud07nz,3,32,NaN,NaN,NaN,NaN
2633928,tj7fzr04mtsoh2ffwbmw86ro4,0,24,NaN,NaN,NaN,NaN
6287290,yvsrxwr3u98rpelhqydllck5g,2,13,2,13,0.0,0.0
5026839,14kja4611hwl5wpoma99o665a,0,15,0,15,0.0,0.0
4932910,fn2ll3syf315m48xh71t3knyj,1,03,3,32,1.0,1.0