In [1]:
# February 11st, 2020
# Script to draw Originality and generality from different Classification systems

In [5]:
import pandas as pd
import numpy as np
import itertools
# import seaborn as sns
# import networkx as nx
import csv
# from graphviz import Digraph
# import igraph
import matplotlib.pyplot as plt
import datetime



import sys
sys.path.append('/home/rkogeyam/scripts/')
sys.path.append('scripts/')

from determinants_scripts import classes, dtypes

src='data/originality_classes.csv'
# src='data/cleanpatent.csv'

# names=['index', 'id', 'cit_received']
# usecols=['id', 'cit_received']
# dtype={'main_group':'int64', 'subgroup':'int64'}
# cols=['patent_id','citation_id', 'cit_delay']
# usecols=['patent_id', 'citation_id']

# df=pd.read_csv(src, parse_dates=['date'], index_col='id', chunksize=10000)

df=pd.read_csv(src, chunksize=10000)

# df=pd.read_csv(src, dtype=dtypes, usecols=usecols, parse_dates=['date'], index_col='id', chunksize=10000)
# df = pd.read_csv(src, chunksize=1000, usecols=usecols, dtypes=dtypes, parse_dates=['date'])

# df = pd.read_csv(src, chunksize=1000,  parse_dates=['date'], error_bad_lines=False)
# df = pd.read_csv(src, usecols=usecols, names=names, chunksize=1000, dtype=dtype, index_col='id')
# df=pd.read_csv(src, usecols=[0, 1, 3], dtype={0:object}, index_col=0, chunksize=1000)

In [6]:
%matplotlib inline

In [7]:
df.get_chunk()

      patent_id  wipo  ipcr  cpc  nber
0       3930271   NaN   NaN  NaN   NaN
1       3930271   NaN   NaN  NaN   NaN
2       3930272   NaN   NaN  NaN   NaN
3       3930272   NaN   NaN  NaN   NaN
4       3930272   NaN   NaN  NaN   NaN
5       3930272   NaN   NaN  NaN   NaN
6       3930272   NaN   NaN  NaN   NaN
7       3930272   NaN   NaN  NaN   NaN
8       3930272   NaN   NaN  NaN   NaN
9       3930272   NaN   NaN  NaN   NaN
10      3930272   NaN   NaN  NaN   NaN
11      3930272   NaN   NaN  NaN   NaN
12      3930272   NaN   NaN  NaN   NaN
13      3930273   NaN   NaN  NaN   NaN
14      3930273   NaN   NaN  NaN   NaN
15      3930273   NaN   NaN  NaN   NaN
16      3930273   NaN   NaN  NaN   NaN
17      3930273   NaN   NaN  NaN   NaN
18      3930273   NaN   NaN  NaN   NaN
19      3930273   NaN   NaN  NaN   NaN
20      3930273   NaN   NaN  NaN   NaN
21      3930274   NaN   NaN  NaN   NaN
22      3930274   NaN   NaN  NaN   NaN
23      3930274   NaN   NaN  NaN   NaN
24      3930275   NaN   NaN  NaN   NaN
25      3930275   NaN   NaN  NaN   NaN
26      3930276   NaN   NaN  NaN   NaN
27      3930276   NaN   NaN  NaN   NaN
28      3930277   NaN   NaN  NaN   NaN
29      3930277   NaN   NaN  NaN   NaN
...         ...   ...   ...  ...   ...
9970    3932366   NaN   NaN  NaN   NaN
9971    3932366   NaN   NaN  NaN   NaN
9972    3932367   NaN   NaN  NaN   NaN
9973    3932367   NaN   NaN  NaN   NaN
9974    3932367   NaN   NaN  NaN   NaN
9975    3932367   NaN   NaN  NaN   NaN
9976    3932368   NaN   NaN  NaN   NaN
9977    3932368   NaN   NaN  NaN   NaN
9978    3932368   NaN   NaN  NaN   NaN
9979    3932368   NaN   NaN  NaN   NaN
9980    3932369   NaN   NaN  NaN   NaN
9981    3932369   NaN   NaN  NaN   NaN
9982    3932369   NaN   NaN  NaN   NaN
9983    3932369   NaN   NaN  NaN   NaN
9984    3932369   NaN   NaN  NaN   NaN
9985    3932369   NaN   NaN  NaN   NaN
9986    3932369   NaN   NaN  NaN   NaN
9987    3932369   NaN   NaN  NaN   NaN
9988    3932369   NaN   NaN  NaN   NaN
9989    3932370   NaN   NaN  NaN   NaN
9990    3932370   NaN   NaN  NaN   NaN
9991    3932370   NaN   NaN  NaN   NaN
9992    3932370   NaN   NaN  NaN   NaN
9993    3932370   NaN   NaN  NaN   NaN
9994    3932371   NaN   NaN  NaN   NaN
9995    3932371   NaN   NaN  NaN   NaN
9996    3932371   NaN   NaN  NaN   NaN
9997    3932371   NaN   NaN  NaN   NaN
9998    3932372   NaN   NaN  NaN   NaN
9999    3932372   NaN   NaN  NaN   NaN

[10000 rows x 5 columns]

In [ ]:
df.category.value_counts()